import Link from 'next/link'
import { Star } from 'lucide-react'

export const metadata = { title: 'Terms of Service — GoHighReview' }

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <nav className="border-b border-border bg-background/80 backdrop-blur-xl">
        <div className="max-w-6xl mx-auto px-6 h-14 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2">
            <div className="w-7 h-7 bg-primary rounded-lg flex items-center justify-center shadow-sm">
              <Star className="w-3.5 h-3.5 text-white fill-white" />
            </div>
            <span className="font-bold text-sm tracking-tight">GoHighReview</span>
          </Link>
          <div className="flex gap-5 text-sm text-muted-foreground">
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link href="/login" className="hover:text-foreground transition-colors">Sign in</Link>
          </div>
        </div>
      </nav>

      <div className="max-w-3xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold tracking-tight mb-2">Terms of Service</h1>
        <p className="text-muted-foreground mb-10">Last updated: March 2026</p>

        <div className="space-y-8 text-foreground">

          <section>
            <h2 className="text-xl font-bold mb-3">1. Acceptance of Terms</h2>
            <p className="text-muted-foreground leading-relaxed">By accessing or using GoHighReview ("the Service"), you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">2. Description of Service</h2>
            <p className="text-muted-foreground leading-relaxed">GoHighReview provides a platform for monitoring, managing, and responding to Google Business Profile reviews. Features include AI-powered reply suggestions, automated replies, review analytics, embeddable widgets, and review collection links.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">3. Account Registration</h2>
            <p className="text-muted-foreground leading-relaxed">You must provide accurate and complete information when creating an account. You are responsible for maintaining the security of your account credentials. You must notify us immediately of any unauthorised use of your account.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">4. Subscription & Billing</h2>
            <p className="text-muted-foreground leading-relaxed">GoHighReview offers paid subscription plans (Lite, Pro, Premium) billed monthly. All plans include a 14-day free trial. You will not be charged until the trial ends. Subscriptions automatically renew unless cancelled. Refunds are handled at our discretion within 7 days of a charge.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">5. Google Business Profile Integration</h2>
            <p className="text-muted-foreground leading-relaxed">By connecting your Google Business Profile, you authorise GoHighReview to read your reviews and post replies on your behalf. You are responsible for ensuring that all replies posted through the Service comply with Google's policies and applicable laws. GoHighReview is not affiliated with Google.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">6. Acceptable Use</h2>
            <p className="text-muted-foreground leading-relaxed mb-2">You agree not to:</p>
            <ul className="list-disc pl-5 space-y-1 text-muted-foreground">
              <li>Use the Service to post fake, misleading, or defamatory reviews</li>
              <li>Attempt to scrape, reverse engineer, or circumvent any security measures</li>
              <li>Use the Service in any way that violates applicable laws or regulations</li>
              <li>Share your account access with others outside your organisation</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">7. AI-Generated Content</h2>
            <p className="text-muted-foreground leading-relaxed">AI reply suggestions are generated by Anthropic Claude and are provided as-is. You are solely responsible for reviewing and approving any AI-generated content before it is posted publicly. GoHighReview is not liable for any AI-generated content that violates third-party policies.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">8. Intellectual Property</h2>
            <p className="text-muted-foreground leading-relaxed">The Service and its original content (excluding your data) are the exclusive property of GoHighReview. You retain ownership of your review data and business information.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">9. Limitation of Liability</h2>
            <p className="text-muted-foreground leading-relaxed">GoHighReview shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. Our total liability shall not exceed the amount paid by you in the 12 months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">10. Termination</h2>
            <p className="text-muted-foreground leading-relaxed">You may cancel your subscription at any time from the billing portal. We reserve the right to suspend or terminate accounts that violate these Terms. Upon termination, your data will be retained for 30 days before deletion.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">11. Changes to Terms</h2>
            <p className="text-muted-foreground leading-relaxed">We may update these Terms at any time. We will notify you of significant changes via email. Continued use of the Service after changes constitutes acceptance of the updated Terms.</p>
          </section>

          <section>
            <h2 className="text-xl font-bold mb-3">12. Contact</h2>
            <p className="text-muted-foreground leading-relaxed">For questions about these Terms, contact us at <a href="mailto:legal@reviewflow.app" className="text-primary hover:underline">legal@reviewflow.app</a>.</p>
          </section>
        </div>
      </div>

      <footer className="border-t border-border">
        <div className="max-w-6xl mx-auto px-6 py-6 flex items-center justify-between text-sm text-muted-foreground">
          <span>© 2026 GoHighReview. All rights reserved.</span>
          <div className="flex gap-5">
            <Link href="/privacy" className="hover:text-foreground transition-colors">Privacy</Link>
            <Link href="/terms" className="hover:text-foreground transition-colors">Terms</Link>
          </div>
        </div>
      </footer>
    </div>
  )
}
